/** Vocativi, titoli e ruoli predefiniti (liste aperte: l’utente può aggiungere valori custom). */

export const CONTACT_VOCATIVES = [
  "Egregio",
  "Egregia",
  "Eccellente",
  "Gentilissimo",
  "Gentilissima",
  "Onorevole",
  "Illustrissimo",
  "Illustrissima",
  "Caro",
  "Cara",
] as const;

export const CONTACT_TITLES = [
  "Architetto",
  "Artista",
  "Avvocato",
  "Cavaliere del Lavoro",
  "Cav. Lav.",
  "Colonnello",
  "Comandante",
  "Commercialista",
  "Conte",
  "Direttore",
  "Direttrice",
  "Dirigente",
  "Don",
  "Dottore",
  "Dottoressa",
  "Dr.",
  "Dr.ssa",
  "Generale",
  "Generale di Brigata",
  "Geometra",
  "Giornalista",
  "Ing.",
  "Ingegnere",
  "Ispettore Capo",
  "Magnifico Rettore",
  "Marchese",
  "Miss",
  "Mister",
  "Monsignore",
  "Mr.",
  "Mrs.",
  "Ms.",
  "Notaio",
  "Onorevole",
  "Presidente",
  "Procuratore",
  "Prof.",
  "Prof.ssa",
  "Professore",
  "Professoressa",
  "Questore",
  "Rabbi",
  "Rag.",
  "Ragioniere",
  "Senatore",
  "Signor",
  "Signora",
  "Signorina",
  "Sindaco",
  "Sindaca",
  "Vicepresidente",
  "Vicesindaco",
  "Vicesindaca",
] as const;

export const CONTACT_ORGANIZATION_ROLES = [
  "Amministratore",
  "Amministratore delegato",
  "CEO",
  "CFO",
  "COO",
  "Direttore",
  "Direttrice",
  "Dirigente",
  "Responsabile",
  "Manager",
  "Coordinatore",
  "Coordinatrice",
  "Segretario",
  "Segretaria",
  "Consigliere",
  "Consigliera",
  "Socio",
  "Collaboratore",
  "Collaboratrice",
  "Consulente",
  "Docente",
  "Ricercatore",
  "Ricercatrice",
  "Addetto stampa",
  "Referente",
] as const;

export const DEFAULT_PRIVACY_CONSENT_DEFS = [
  { id: "data_processing", label: "Consenso trattamento dati base" },
  { id: "newsletter", label: "Consenso trattamento dati newsletter" },
  { id: "marketing", label: "Consenso trattamento dati marketing" },
  { id: "third_party", label: "Consenso cessione a terzi" },
] as const;

export type DefaultPrivacyConsentId =
  (typeof DEFAULT_PRIVACY_CONSENT_DEFS)[number]["id"];
